### ISSUE TITLE
How can we make this into a html image map?

### ISSUE THREAD

**Issue by pjebs** [nikolaydubina/calendarheatmap#9]
It would be great if we can detect clicks on any given box and get the corresponding date and react to the click.
To do that, it'd be great to get the coordinates of each box.

**Comment by nikolaydubina** [comment]
Hi, current version does not support any interactive behavior. This was intentional for the first version since static images are portable, they work virtually on all devices, platforms, and many apps. Interactive (SVG, SGV+CSS, HTML, HTML+JS) on other hand SVG and other interactive formats require browser to render and run, can not be rendered in Messages, can not be stored in Photos, had to rely on Files that does not render it either.

But I see your point, few people already asked about interactive functions close to what you describe. Can you provide more details on how you plan to use it? Do you do server-side rendering of webpage? Is it on mobile? Does SVG work?

**Comment by pjebs** [comment]
I guess I was just trying to make it more useful and so something like the heatmap found on github, where you can hover over an individual box and trigger and event and also click on it.

Something like this: https://www.jonathan-petitcolas.com/2013/07/18/create-clickable-svg-france-regions-map.html

**Comment by pjebs** [comment]
With svg you should be able to return the coordinates of each box. Even if the image is scaled, we can adjust the coordinates.

**Comment by nikolaydubina** [comment]
Hi, @pjebs SVG is supported now.
